GET http://localhost:8080/users?name=Bruno

###
GET http://localhost:8080/users/4

###
POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{
    "name": "Wesley",
    "mail": "wesley@fullcycle.com"
}